title: "Filter"
description: |
  Helps the user filters products if they are looking at all the products on the site. It goes in the top left corner of the page, under the navigation. In the code it goes above all the main content.
