permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Milk & Honey"
  description: |
    A natural solution.
  font_url: "https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400i,700&display=swap"
  colors:
    background: "--color-secondary-light"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.secondary: |
      PT Sans Narrow is only to be used for highlight text: headings, buttons, banners, etc.
    color.primary: |
      The Primary colours represent herbivores & plants & greenery. They should be used for text and in foregrounds.
    colors.secondary: |
      The secondary colours are more neutral, continuing with the earth tones, and should be used for backgrounds.
