permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Wick It"
  description: |
    "An online candle store that offers scents that immerse you into nature"
  font_url: "https://fonts.googleapis.com/css?family=Montserrat:400,500"
