permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "MUSHROOM BOY"
  description:  |
    A unisex t-shirt, hoodie and jacket company. Dedicated to inspiring customers and giving them a chance to express themselves with their unique clothing.
  font_url: "https://use.typekit.net/cjq1zsh.css"
  colors:
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Futura was selected because it is a modern typeface that is easy to read and expressive. Futura is used for all headings under H2 and body copy.
    typefaces.secondary: |
      FF Prater Block was selected because it is a fun and expressive typeface that shows off the expected feel of the company. FF Prater Block is used for H1s and the company's name in the header. It should not be used at small sizes!
    colors.primary: |
      The primary colours are black and an off-white to keep the website sleek looking.
    colors.accent: |
      The accent colours are brighter and pop off the pages to add intrest and also aide the consumer in easily identifying key elements of any page.
  layouts:
    default: |
      This is the layout to be used on all pages. To switch to the large banner add `show_big_banner: true` to the top of the page.
    product: |
      This is the layout to be used on every product page. It will display all information about the product once a product has been selected.
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
