permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Mushroom Boy"
  description:  |
    A unisex t-shirt, hoodie and jacket company. Dedicated to inspiring customers and giving them a chance to express themselves with their unique clothing.
  font_url: "https://use.typekit.net/cjq1zsh.css"
  rationales:
    typeface.primary: |
      Futura was selected because it is a modern typeface that is easy to read and expressive. Futura is used for all headings under H2 and body copy.
    typefaces.secondary: |
      FF Prater Block was selected because it is a fun and expressive typeface that shows off the expected feel of the company. FF Prater Block is used for H1s and the company's name in the header. It should not be used at small sizes!
