permalink: pretty
theme: jekyll_patternbot

patternbot:
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the websites primary header & footer.
  title: "Coze"
  description: |
    Coze sells only the best hand-crafted home enhancers from artists around the Ottawa area.
  font_url: "https://fonts.google.com/?selection.family=Muli:400,700|:400,700"
  colors:
    background: "--color-secondary"
    accent: "--color-primary"
    patterns:
      fields:
        - name: heading
          type: string
          example: "Brilliant, stunning, bright"
        - name: text
          type: string
          example: "Geological marvels: gems, crystals, diamonds, geodes and much more!"
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary: |
      Crimson Text is being used as my primary font because of it's large x-height and friendly feel. It matches well with the secondary typeface (Multi). Crimson Text is used for all body copy and most situations.
    typefaces.seconary: |
      Multi is only to be used for highlighting text: headings, buttons, banners, etc.
    colors.primary: |
      The primary colours chosen as a calming turquoise colour. This colours goes with the theme of home and bath products creating a tranquil, comfortable environment.
    colors.secondary: |
      The secondary colours are more neutral, continuing with the calming effect of the turquoise colour and complimenting it well.
      masthead: |
      This pattern should be used on every page as the main header.
      footer: |
      This pattern should be used on every page as the main footer.

  collections:
    products:
      output: true

      defaults:
        - scope:
            path: _products
          values:
            layout: product
