permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: SHOP BY AIR
  description: |
    SDFGSDFGSDFG
  font_url: "https://fonts.googleapis.com/css?family=Montserrat"
  colors:
    background: "color-secondary"
    accent: "--color-primary-light"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Montserrat was selected because it is a light typeface, creating a simple and clean look to the minimilistic website. This will be the only typeface that would be used.
    colors.primary: |
      The primary colours represent the air element. A color contrast with the blue hues against the white background would be ideal to create this website. These colours would be used for the banners and navigation bar.
    colors.secondary: |
      The secondary colour creates a color contrast, not only against the white, but against the primary colours. This would be used for buttons, or to highlight links.
