permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: Potato Alchemy
  description: |
    Charmed Potatoes that remove nasty hexes and improve your fortune!
  font_url: "https://fonts.googleapis.com/css?family=Mystery+Quest|Montserrat:300,400,700"
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header & footer.
  colors:
    background: "--color-background"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-secondary-light"
  rationales:
    typefaces.primary: |
      Montserrat was selected because as the body text it is easy to read and it complements the header typeface.
    typefaces.secondary: |
      Mystery Quest was used for the headers to give the website a more bewitched/magical feel.
    colors.primary: |
      The primary colour is a purple to represent mysticism and spells. It is a colour that is used frequently on competitor sites and in pop culture referencing magic.
    colors.secondary: |
      The secondary colour is a kind of turquoise that is frequently used in movies and imagry for potions, ampulets and other magical items.
    colors.neutral: |
      These colours are used to aid and enhance the primary and secondary colours.
collections:
    products:
        output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
