permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Coze"
  description: |
    Coze sells only the best hand-crafted home enhancers from artists around the Ottawa area.
  font_url: "https://fonts.google.com/?selection.family=Muli:400,700|:400,700"
  colors:
    background: "--color-primary"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Crimson Text is being used as my primary font because of it's large x-height and friendly feel. It matches well with the secondary typeface (Multi). Crimson Text is used for all body copy and most situations.
    typefaces.seconary: |
      Multi is only to be used for highlighting text: headings, buttons, banners, etc.
    colors.primary: |
      The primary colours chosen as a calming turquoise colour. This colours goes with the theme of home and bath products creating a tranquil, comfortable environment.
    colors.secondary: |
      The secondary colours are more neutral, continuing with the calming effect of the turquoise colour and complimenting it well.
