permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.google.com/?query=pt+sans&selection.family=Oswald:300,400,700|PT+Sans:400,700"
  colors:
    background: "--color-neutral-beige"
    accent: "--color-accent"
    patterns:
      brand.logos: "--color-whatever"
      brand.colors: "#fff"
  rationales:
    typefaces.primary: |
      The primary typeface is mainly for the use of headings and more prominent statements or parts of text that should be emphasized in hierarchy. This should be used for more prominent statements as well.
    typefaces.secondary: |
      The secondary font is used for the body copy and more subtle statements on the website. For example: small descriptions, information, etc. It can also bbe used for the details on cards, lists, navigations.
    colors.primary: |
      Colour is the The primary colour is meant to be used for the main sections and subheadings of content, in order to implement the brand and it's identity.
    colors.secondary: |
      The secondary colour is used as a back drop for sub-sections in the website in order to tie together the look and feel of the brand.
    layouts:
      default: |
        The default layout should be for almost every page, it includes the website's primary header and footer.
      header: |
        The header will appear on each page of the website in order to remain cohesive and accessible of each section for the user. It contains the navigation (home,products,checkout,etc).
      footer: |
        The footer is similar to the header, where it should appear on every page of the website. It is found at the bottom of the page and lists off the subcategories of the website's sections. This is also where to sign up for newsletters and discover more options.

collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
