permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.google.com/?query=pt+sans&selection.family=Oswald:300,400,700|PT+Sans:400,700"
  colors:
    background: "--color-primary-light"
    accent: "--color-accent"
    patterns:
      brand.logos: "--color-whatever"
      brand.colors: "#fff"
  rationales:
    typefaces.primary: |
      The primary typeface is mainly for the use of headings and bolder statements.
    typefaces.secondary: |
      The secondary font is used for the body copy
    color.primary: |

    color.secondary: |
