permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Mushroom Boy"
  description:  |
    A unisex t-shirt, hoodie and jacket company. Dedicated to inspiring customers and giving them a chance to express themselves with their unique clothing.
  font_url: "https://use.typekit.net/cjq1zsh.css"
