permalink: pretty
theme: jekyll_patternbot

patternbot:

  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header & footer.
    product: |
      The products layout should be used for products only.

  title: SHOP BY AIR
  description: |
    This website provides clothing and home decors based on the Air elements of the Zodiac sign (Gemini, Libra, and Aquarius). The logo is the air symbol to represent the three Zodiac signs.
  font_url: "https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat:400,400i,500,500i,700,700i"
  colors:
    background: "--color-neutral-beige"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Montserrat was selected because it is a light typeface, creating a simple and clean look to the website. This will be the only typeface that would be used.
    colors.primary: |
      The primary colours shown represent the Air elements of the Zodiac sign (Gemini, Libra, and Aquarius). A colour contrast with the cool colours (such as white text) would be ideal for this website. The Primary colour will be used for the top header navigation as well as the footer. The Primary Light is used to highlight the buttons.
    colors.secondary: |
      This secondary colour is used to highlight the links located at the top header.
    colors.accent: |
      The Red is used to let users know which items are on sale.
    colors.neutral: |
      This colour is used as a secondary background colour against the white default background colour. This will create a slight contrast against the white default background colour. The product cards will have this background colour.

collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
