permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Egg"
  description:
    Official Egg merchandise! Egg is the little prince from another planet.
  font_url: "https://fonts.googleapis.com/css?family=Lato:400,400i,700|Roboto:400,700"
  colors:
    background: "--color-neutral-light"
    accent: "--color-primary"
  rationales:
    typefaces.primary: |
      Lato was selected because it uses classical proporations while still being sleek—perfect for the prince online. Lato is to be used for all body copy.
    typefaces.secondary: |
      Roboto is to be used only in highlighting text: headers, buttons, etc.
    colors.primary: |
      The primary colours are the colours from Egg's body. They should be used for text and in the foreground.
    colors.secondary: |
      The secondary colours are the colours from Egg's crown. They should be used for minor highlights to stand out against the primary colours.
    colors.neutral: |
      The neutral colors are the light colours from Egg's body. They should be used in the background.
  layouts:
    default: |
      The default layout should be used for almost every page. It contains the header and footer.
collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
