permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: Potato Alchemy
  description: |
    Charmed Potatoes that remove nasty hexes and improve your fortune!
  font_url: "https://fonts.googleapis.com/css?family=Mystery+Quest|Noto+Serif+SC:300,400,700"
