permalink: pretty
theme: jekyll_patternbot

patternbot:

  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header & footer.

  title: SHOP BY AIR
  description: |
    Shop By Air is dedicated to providing stylish designs with the best quality materials for our loyal customers. Not only are the products affordable for all, but have been recieving rave reviews. Be sure to download our app on your mobile phone to be uploaded on the latest trends, and be notified when deals are happening. The air signs (Gemini, Libra, and Aquarius) will surely love these gifts!
  font_url: "https://fonts.googleapis.com/css?family=Montserrat"
  colors:
    background: "--color-neutral-beige"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Montserrat was selected because it is a light typeface, creating a simple and clean look to the minimilistic website. This will be the only typeface that would be used.
    colors.primary: |
      The primary colours represent the air element. A color contrast with the blue hues against the white background would be ideal to create this website. These colours would be used for the banners and navigation bar.
    colors.secondary: |
      The secondary colour creates a color contrast, not only against the white, but against the primary colours. This would be used for buttons, or to highlight links.
    colors.accent: |
      The primary accent colour red is used for the cancel button.
    colors.neutral: |
      The neutral colour is used mainly used for the background colour of the website.
    collections:
      clothes:
        output: true

    defaults:
      - scope:
        path: _clothes
      values:
        layout: crop-top
