permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.google.com/?query=pt+sans&selection.family=Oswald:300,400,700|PT+Sans:400,700"
  colors:
    background: "--color-neutral-beige"
    accent: "--color-accent"
    patterns:
      brand.logos: "--color-whatever"
      brand.colors: "#fff"
  rationales:
    typefaces.primary: |
      The primary typeface is mainly for the use of headings and more prominent statements or parts of text that should be emphasized in hierarchy.
    typefaces.secondary: |
      The secondary font is used for the body copy and more subtle statements on the website. For example: small descriptions, information, etc.
    colors.primary: |
      The primary colour is meant to be used for the main sections and subheadings of content, in order to implement the brand and it's identity. This should be displayed throughout the website as a unified whole.
    colors.secondary: |
      The secondary colour is used as a back drop for sub-sections in the website in order to tie together the look and feel of the brand.
