- title: Fiery Candle
  price: $13.99
  image: /images/fiery-candle.jpg

- title: Palm Candle
  price: $13.99
  image: /images/palm-candle.jpg

- title: Woods Candle
  price: $13.99
  image: /images/woods-candle.jpg

- title: Mantra Candle
  price: $13.99
  image: /images/mantra-candle.jpg

- title: Tang Candle
  price: $13.99
  image: /images/tang-candle.jpg

- title: Rivers Candle
  price: $13.99
  image: /images/rivers-candle.jpg

- title: Fiery Wax Melt
  price: $9.99
  image: /images/fiery-wax-melt.jpg

- title: Rivers Wax Melt
  price: $9.99
  image: /images/rivers-wax-melt.jpg

- title: Woods Wax Melt
  price: $9.99
  image: /images/woods-wax-melt.jpg
