title: "Footer"
description: |
  Navigation, social links and copyright that stays at the botton of every page.

patterns:
  footer:
    title: "Footer"
    description: |
      Holds all information that should appear at the bottom of every page. It stays the same from page to page.
