title: "Buttons"
description: |
  Buttons sould be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Buttons for the shirts pages.
  ghost:
    title: "Ghost"
    description: |
      Buttons for the jackets pages.
  light:
    title: "Light"
    description: |
      Buttons for the hoodies pages.
