title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
    background: "--color-secondary"
    fields:
      - name: text
        type: string
        example: "clothes"
      - name: url
        type: url
        example: "/clothes/"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for cards to view products.
    background: "#fff"
    width: "12em"
  light:
    title: "Light"
    description: |
      The light button is used for banners, where it will be placed in front of dark images to create colour contrast.
    background: "--color-primary"
    width: "12em"
