title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Purchase Button"
    description: |
      This is purchase button is used for the product cards.
    fields:
      - name: text
        type: string
        example: "clothes"
  light:
    title: "Signs button"
    description: |
      These three buttons will be used on the banners for the Air signs (Gemini, Libra, and Aquarius), located in the "Zodiac" page. The buttons will help navigate the users to different Zodiac signs and continue to shop based on a specific sign.
    background: "#3b6d87"
