title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is require. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
    width: "12em"
  light:
    title: "Light"
    description: |
      The light button is for dark backgrounds, where it will be used instead of the basic button.
    width: "12em"
  magic:
    title: "Magic"
    description: |
      The Magic button is for entertainment. It should only be used once on a page and ideally with no other buttons on the same page.
    padding: "2em 0"
    width: "12em"
  form-btn:
    title: "Send Form"
    description: |
      Use this button at the end of any forms
    width: "12em"
  cart:
    title: "Shopping Cart"
    description: |
      Use this button on mobile to access the shopping cart or within product item cards
    width: "12em"
