patterns:
  product-card:
    width: 400
    description: |
      The product card is used on the product listings page to display each individual product. Each product card will have it's own separate content and will cater to different items.
    fields:
      - name: data
      type: object
      data:
        source: "site.products[0]"
        type: Product
