title: "Figures"
description: |
  The form can be used when creating a checkout page, contact page, or a survey

patterns:
  product-details:
    fields:
      - name: heading
        type: string
        example: "Genius Potion"
      - name: text
        type: string
        example: "Place in water for 24 hrs before drinking to stimulate genius part of brain"
      - name: image
        type: url
        example: "/images/potato.jpg"
    title: "Product Details"
    description: |
      Use this layout for the product description
