title: "Forms"
description: |

patterns:
  confirmation:
    title: "Confirmation"
    description: |
      This would be used at the end of the form (but before the purchase button). This states that the information that was currently filled out in the form is correct.
