title: "Forms"
description: |
  Forms should be used when purchasing an item and information is required for the purchase.

patterns:
  confirmation:
    fields:
      - name: text
        type: string
        example: "I agree with the information above"
    title: "Confirmation"
    description: |
      This field is a checkbox to be used with the button only at the end of the form to confirm all the information entered is correct. Only with forms.
  input:
    fields:
      - name: text
        type: string
        example: "Name"
    title: "Input"
    description: |
      These fields are all the information needed to be filled up for a purchase.
  provinces:
    title: "Provinces"
    description: |
      Only use this field for an easy way to put in your Province in a form.
  phone:
    fields:
      - name: text
        type: string
        example: "Phone"
    title: "Phone"
    description: |
      This input is to be used only for phone numbers.
  textarea:
    fields:
      - name: text
        type: string
        example: "Write a message"
    title: "Text Area"
    description: |
      This field is only the be used with a form to add a message attached with the gift.
  email:
    title: "Email"
    fields:
      - name: text
        type: string
        example: "Email"
    description: |
      This input is to be used only for emails.
