title: "Navigation"
description: |
  These are navigation patterns used for promotional discount on items, or to be used on smaller screens.
patterns:
  toggle:
    title: "Header navigation"
    description: |
      On a large screen, the links on the leader will appear horizontally. On smaller screens, the navigation will switch to a toggle nav. Also, the top will read "Take advantage of the FREE SHIPPING world wide" on a large screen, but will reduce to "FREE SHIPPING world wide" on a smaller screen.
  radial:
    title: "Radial buttons"
    description: |
      After user makes a purchase, this will be used to show items that are currently on sale. It serves as a recommended item that they might also like to purcahse. Users will click on the radial buttons to view a different product on sale.
    background: "#fff"
