title: "Navigation"
description: |
  Navigations are used to guide users through the website and find information.

patterns:
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      Breadcrumbs show the path that was taken and it allows them to return to the previous pages easily.
    fields:
      - name: main
        type: string
        example: "Products"
      - name: secondary
        type: string
        example: "Stickers"
      - name: item
        type: string
        example: "Egg"
      - name: url-main
        type: url
        example: "/products/"
      - name: url-secondary
        type: url
        example: "/stickers/"
  page-nav:
    title: "Page Navigation"
    description: |
      Page navigation allows the user to move between pages when there are more products available.
    fields:
      - name: current1
        type: string
        example: "current-page"
        required: false
      - name: current2
        type: string
        example: "current-page"
        required: false
      - name: current3
        type: string
        example: "current-page"
        required: false
