title: "Photo Array"
description: |
  Photo arrays should be used on product pages to display the products and the highlights of the product.

patterns:
  basic:
    fields:
      - name: imagemain
        type: string
        example: "little-egg.png"
      - name: image2
        type: string
        example: "little-egg.png"
      - name: image3
        type: string
        example: "little-egg.png"
      - name: image4
        type: string
        example: "little-egg.png"
      - name: image5
        type: string
        example: "little-egg.png"
