title: "Figures"
description: |
  The form can be used when creating a checkout page, contact page, or a survey

patterns:
  founder-bg:
    fields:
      - name: text
        type: string
        example: |
          Alchemy Potatoes are magical potatos created by Davey Seeds. A long time alchemist who was tired of phoney charms. Alchemy Potatoes are specially designed so that you can see their magic work in action. Each potato is curated to protect you from specific hexs, spells, curses, potions, and incantations.
    title: "Inline figure/figcaption"
    description: |
      Use this type of figure when you want the text to sit beside the image at larger screen sizes
  info-bucket:
    fields:
      - name: heading
        type: string
        example: "Avoid Time Travel"
      - name: text
        type: string
        example: "From faulty crystals"
      - name: image
        type: url
        example: "/images/time-travel.png"
    title: "block-figure"
    description: |
      Use this type of figure when you always want the text to sit below the image
    width: "20em"
