title: "Banners"
description: |
  A banner is a section of highlighted information, usually to let the user know a task is complete, or that an action has been taken. Banners are for landing pages, and to acknoledge completion of an action.

patterns:
  front-banner:
    title: "call-to-action"
    description: |
      Invites user to act on advertising. Always on landing page.
