title: "Banners"
description: |
  A banner is a section of highlighted information, usually to let the user know a task is complete, or that an action has been taken. Banners are for landing pages, and to acknoledge completion of an action.

patterns:
  front-banner:
    fields:
      - name: heading
        type: string
        example: "Brilling, stunning, bright"
      - name: text
        type: string
        example: "Geological marvels: gems, crystals, diamonds, geodes, and much more!"
      - name: button_text
        type: string
        example: "Shop"
        required: false
      - name: button_url
        type: button_url
        example: "/cream/"
