title: "Banners"
description: |
  Banners should only be used for important information.

patterns:
  banner:
    title: "Top Page Banner"
    description: |
      The top page banners should only be used when there's something new or important that wants the attention of the user.
    fields:
      - name: heading
        type: string
        example: "The Little Prince"
      - name: text
        type: string
        example: "He's from another planet but he's here to stay."
      - name: image
        type: string
        example: "egg/little-prince.png"
      - name: button_text
        type: string
        example: "Buy an Egg"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
  call-to-action:
    title: "Call to Action"
    description: |
      The call to action banners should be used when there's something that the site wants the user to do like sign up.
    fields:
      - name: text
        type: string
        example: "Special: when signing up you get a 10% discount on your first order!"
